### ISSUE TITLE
What you will work on

### ISSUE THREAD

**Issue by onzfonz** [maximomacchi/Afterdark#5]
Issues #4, #3, & #2, were complete and detailed.  However, the scope was I believe a bit too small for what I'm looking for for this project.  What I'd like you to do instead is to try to implement a new type of enemy into the game.  Have it be someone that flies, or constantly jumps as they move along, instead of just having them walk everywhere.  

Let me know if you have any questions about it, but you'll have to possibly modify enemy (and make a new enemy style class), and a couple of your other classes around your game.

**Comment by maximomacchi** [comment]
*note: new feature is on branch `new-enemy-COMP-129`, not `master` branch
Steps to test the new feature:
1. Open the entire repository in Eclipse
2. Run MainApplicaiton
3. When the main menu appears, click the Play button
4. As you progress through the level, there will be some enemies that move and some that jump up and down.
5. If you want enemies to jump more frequently, you can change the difficulty through the Settings page in the main menu
